#!/usr/bin/env python3
"""Generate the legacy prompt URL from the maintained sources."""
import argparse
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
SOURCES = ('SKILL.md', 'prompt/rules.md', 'prompt/standing-decisions.md')
TARGET = ROOT / 'prompt/SKILL.md'


def render():
    chunks = ['<!-- Generated by tools/export_prompt.py; do not edit. -->\n']
    for relative in SOURCES:
        text = (ROOT / relative).read_text(encoding='utf-8')
        if relative == 'SKILL.md':
            text = text.split('---', 2)[-1].strip().replace('(prompt/', '(')
        chunks.append('<!-- Source: ' + relative + ' -->\n\n' + text.strip() + '\n')
    return '\n---\n\n'.join(chunks)


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--check', action='store_true')
    args = parser.parse_args()
    expected = render()
    if args.check:
        if not TARGET.is_file() or TARGET.read_text(encoding='utf-8') != expected:
            raise SystemExit('Prompt is stale; run python3 tools/export_prompt.py')
        print('Prompt matches maintained sources')
    else:
        TARGET.write_text(expected, encoding='utf-8')
        print('Generated prompt/SKILL.md')


if __name__ == '__main__':
    main()
